services:
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ${FRONTEND_ROOT}:/node/app
    ports:
      - ${FRONTEND_PORT}:5173
    stdin_open: true
    tty: true
    build:
      target: starter
      context: ./
      dockerfile: ./services/frontend/Dockerfile
      args:
        - ROOT=${FRONTEND_ROOT}

  backend:
    volumes:
      - ${BACKEND_ROOT}:/node/app
    depends_on:
      - database
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    build:
      target: starter
      context: ./
      dockerfile: ./services/backend/Dockerfile
      args:
        - ROOT=${BACKEND_ROOT}
    networks:
      backend:
        aliases:
          - "backend"
    dns:
      - 8.8.8.8

  database:
    stdin_open: true
    tty: true
    volumes:
      - kdb:/var/lib/postgresql/
    build:
      context: ./services/database
      args:
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_USERPWD=${DB_USERPWD}
    networks:
      backend:
        aliases:
          - postgresql

networks:
  backend:


volumes:
  kdb:
